PULP Event Load Extension Version 1
openhwgroup/corev-binutils-gdb pull request #50
Opened 2022-10-13 14:48 UTC by NandniJamnadas

2022-10-13 15:12 UTC, jeremybennett requested changes
Overall, looks good. A couple of changes

1. You are lacking a GNU compliant commit message for the documentation commit.
2. You need some assembler tests of the validity of the extension.
    - is ELW only enabled when `-march=...Xcorevelw`
 3. You should include your regression test results as a comment on the PR.

2022-10-14 08:14 UTC, jeremybennett commented on bfd/elfxx-riscv.c
> +      return "xcorevelw' or `xcorev";
TBD - what does `corev` mean when we have new versions of the tool chain. Suggestion
- `corev1p0`: Version 1 of all 5 CV32E40Pv1 extensions
- `corev2p0`: Version 2 of all 5 CV32E40Pv1 extensions and version ` of all C32E40Pv2 extensions

2022-10-14 08:15 UTC, jeremybennett commented on gas/doc/c-riscv.texi
>  @end itemize
Add `corev` as a catchall.

2022-10-14 08:19 UTC, jeremybennett commented on gas/testsuite/gas/riscv/cv-elw-fail.s
> +    cv.elw x5,2048(x6)
What about negative offsets?

2022-10-15 08:49 UTC, NandniJamnadas commented
1. "You are lacking a GNU compliant commit message for the documentation commit":
https://github.com/openhwgroup/corev-binutils-gdb/pull/50/commits/a9405b6ac6ac60f26acbfe3cd280b4e8764ed4bb
2. "You need some assembler tests of the validity of the extension":
 https://github.com/openhwgroup/corev-binutils-gdb/pull/50/commits/6f184a9a70ec5fecde3adfec79776896fd3dcce2
3. "You should include your regression test results as a comment on the PR".
GNU Assembler Results:
```
| Category             | Baseline | Curr. Week |       Delta |
| :------------------- | -------: | ---------: | ----------: |
| Expected passes      |      785 |        788 |          +3 |
| Unexpected failures  |        - |          - |           - |
| Unexpected successes |        - |          - |           - |
| Expected failures    |       23 |         23 |           - |
| Unresolved testcases |        - |          - |           - |
| Unsupported tests    |        9 |          9 |           - |
```

2022-10-19 11:54 UTC, jeremybennett commented on gas/doc/c-riscv.texi
>  @end itemize
All fixed.

2022-10-19 11:56 UTC, jeremybennett approved these changes

2022-10-19 11:57 UTC, merged

2022-10-19 11:57 UTC, jeremybennett commented
All looks good. OK to merge.