Updated hardware loop instruction encodings
openhwgroup/corev-binutils-gdb pull request #70
Opened 2023-01-31 13:45 UTC by MaryBennett

==Related Issues==
Issues #63 & #64 

==Commit==

Changed how uimml in cv.starti, cv.endi, and cv.setup was encoded to match the specification. Did the same for uimmS in cv.setupi.

Files Changed:

bfd:
 * elfxx-riscv.c: Changed the CORE-V hardware loop relocations to rightshift 2.

gas/config:
 * tc-riscv.c: Changed encoding of uimmL and uimmS in hardware loop instructions.

gas/testsuite/gas/riscv:
 * cv-hwlp-endi.d: Updated tests.
 * cv-hwlp-endi.s: Likewise.
 * cv-hwlp-fail-operand-01.l: Likewise.
 * cv-hwlp-fail-operand-01.s: Likewise.
 * cv-hwlp-fail-operand-02.l: Likewise.
 * cv-hwlp-fail-operand-03.l: Likewise.
 * cv-hwlp-fail-operand-03.s: Likewise.
 * cv-hwlp-fail-operand-04.l: Likewise.
 * cv-hwlp-fail-operand-10.s: Likewise.
 * cv-hwlp-march-rv32i-xcorev.d: Likewise.
 * cv-hwlp-setup.d: Likewise.
 * cv-hwlp-setup.s: Likewise.
 * cv-hwlp-setupi.d: Likewise.
 * cv-hwlp-setupi.s: Likewise.
 * cv-hwlp-starti.d: Likewise.
 * cv-hwlp-starti.s: Likewise.

ld/testsuite/ld-riscv-elf:
 * cv-hwlp-endi.d: Updated tests.
 * cv-hwlp-setup.d: Likewise.
 * cv-hwlp-setupi.d: Likewise.
 * cv-hwlp-starti.d: Likewise.

opcodes:
 * riscv-dis.c: Changed how the relocation is printed.

==Results==

===GAS===
| Category             | Previous | With commit | Delta |
| -------------------: | -------: | ----------: | ----: |
| Expected passes      |     1270 |        1270 |  - |
| Unexpected failures  |       - |          - |     - | 
| Unexpected successes |        - |           - |     - | 
| Expected failures    |        23|          23 |     - | 
| Unresolved testcases |        - |         - |     - | 
| Unsupported tests    |      9 |        9 |     - |

===LD===
| Category             | Previous | With commit | Delta |
| -------------------: | -------: | ----------: | ----: |
| Expected passes      |     584 |        588 |  +4 |
| Unexpected failures  |       18 |          14 |    -4 | 
| Unexpected successes |        - |           - |     - | 
| Expected failures    |        18 |           18 |     - | 
| Unresolved testcases |        - |           - |     - | 
| Unsupported tests    |      219 |         219 |     - |

The additional four passes in LD are due to:
* opcode encoding had not been updated to cv32e40pv2

2023-02-06 14:41 UTC, jeremybennett commented
@MaryBennett - what are the remaining 14 unexpected failures?

2023-02-06 16:02 UTC, MaryBennett commented
Two of the failures are caused by ```cv.bneimm``` and ```cv.beqimm```. These are fixed in PR #72.

2023-02-06 16:08 UTC, MaryBennett commented
Here are the new results:
| Category             | Previous | With commit | Delta |
| -------------------: | -------: | ----------: | ----: |
| Expected passes      |    427  |     431 |  +4 |
| Unexpected failures  |    6 |   2 |    -4 | 
| Unexpected successes |        - |           - |     - | 
| Expected failures    |      16 |       16 |     - | 
| Unresolved testcases |      3 |         3 |     - |
| Untested testcases | 20 | 20 | - | 
| Unsupported tests    |      200 |        200 |     - |

2023-02-06 16:13 UTC, jeremybennett requested changes
Generally looks good to me.  In the commit message you need more context about why this is happening.  You need to explain that the instructions have new encodings for the CV32E40Pv2 and give a link to the official documentation.

There are a couple of things that need fixing.

2023-02-06 16:13 UTC, jeremybennett commented on gas/testsuite/gas/riscv/cv-hwlp-fail-operand-01.l
> +.*: Error: 20394 constant out of range for cv.setup, range:\[0, 16383\]
Surely the range is [0,16380] since the value must be 4-byte aligned?

2023-02-06 16:13 UTC, jeremybennett commented on gas/testsuite/gas/riscv/cv-hwlp-fail-operand-03.s
> +# Branch offset must be an even integer in range:[0, 127]
This is tricky.  The offset is a word offset, and clearly the intention is that this is symbolic.  The interpretation we have taken is that if specified literally, it is an offset in bytes (reasonably enough), which means, given it is a 5-bit unsigned value, it should be in the range 0-31 words, (or 0-124 bytes, and a multiple of 4-bytes).  So I think the message should be "Branch offset must be an integer multiple of 4 in range:[0, 124]".

You also need to look at linker tests of hardware loop, since this does not correctly test when a symbolic offset resolves to be too large.  That's not something for this patch, but I'll raise it as an issue in due course.

2023-02-06 16:17 UTC, jeremybennett commented on gas/testsuite/gas/riscv/cv-hwlp-fail-operand-03.s
> +# Branch offset must be an even integer in range:[0, 127]
Raised issue [#73]

2023-02-06 16:52 UTC, MaryBennett commented on gas/testsuite/gas/riscv/cv-hwlp-fail-operand-03.s
> +# Branch offset must be an even integer in range:[0, 127]
Thank you. I've changed this.

2023-02-06 16:52 UTC, MaryBennett commented on gas/testsuite/gas/riscv/cv-hwlp-fail-operand-01.l
> +.*: Error: 20394 constant out of range for cv.setup, range:\[0, 16383\]
Changed

2023-02-09 10:27 UTC, jeremybennett approved these changes
All issues have been addressed. Good to merge.

2023-02-09 10:28 UTC, merged